import dress_1 from '../assets/dress_images/dress_1.jpeg';
import dress_2 from '../assets/dress_images/dress_2.jpeg';
import dress_3 from '../assets/dress_images/dress_3.jpeg';
import dress_4 from '../assets/dress_images/dress_4.jpeg';
import dress_5 from '../assets/dress_images/dress_5.jpeg';
import dress_6 from '../assets/dress_images/dress_6.jpeg';
import dress_7 from '../assets/dress_images/dress_7.jpeg';
import dress_8 from '../assets/dress_images/dress_8.jpeg';
import dress_9 from '../assets/dress_images/dress_9.jpeg';
import dress_10 from '../assets/dress_images/dress_10.jpg';
import dress_11 from '../assets/dress_images/dress_11.jpeg';
import dress_12 from '../assets/dress_images/dress_12.jpeg';
import dress_13 from '../assets/dress_images/dress_13.jpeg';
import dress_14 from '../assets/dress_images/dress_14.jpeg';
import dress_15 from '../assets/dress_images/dress_15.jpeg';
import dress_16 from '../assets/dress_images/dress_16.jpeg';

const data = [
  {
    id: 1,
    img: dress_1,
    title: "Nike Air Monarch IV",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "Off-White",
    category: "Henley Shirts",
    colors: ["Off-White", "Black", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4,
    description: "Comfortable and stylish sneakers for everyday wear.",
    material: "Leather",
    weight: "500g",
    dimensions: "30 x 20 x 10 cm"
  },
  {
    id: 2,
    img: dress_2,
    title: "Nike Air Vapormax Plus",
    reviews: 89,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "red",
    category: "Henley Shirts",
    colors: ["Red", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 5,
    description: "Lightweight running shoes with excellent cushioning.",
    material: "Mesh",
    weight: "400g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 3,
    img: dress_3,
    title: "Nike Waffle One Sneaker",
    reviews: 56,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "green",
    category: "Henley Shirts",
    colors: ["Green", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4,
    description: "Classic waffle sole for superior traction.",
    material: "Suede",
    weight: "450g",
    dimensions: "29 x 19 x 9 cm"
  },
  {
    id: 4,
    img: dress_4,
    title: "Nike Running Shoe",
    reviews: 78,
    prevPrice: 140,
    newPrice: 200,
    company: "Adidas",
    color: "black",
    category: "Henley Shirts",
    colors: ["Black"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "High-performance running shoes for all terrains.",
    material: "Mesh",
    weight: "380g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 5,
    img: dress_5,
    title: "Flat Slip On Pumps",
    reviews: 45,
    prevPrice: 140,
    newPrice: 200,
    company: "Vans",
    color: "green",
    category: "Dress Shirts",
    colors: ["Green", "Black", "Brown"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Comfortable slip-on shoes for casual wear.",
    material: "Canvas",
    weight: "350g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 6,
    img: dress_6,
    title: "Knit Ballet Flat",
    reviews: 67,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Dress Shirts",
    colors: ["Black", "White", "Pink"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Soft and flexible ballet flats for all-day comfort.",
    material: "Knit",
    weight: "300g",
    dimensions: "26 x 16 x 6 cm"
  },
  {
    id: 7,
    img: dress_7,
    title: "Loafer Flats",
    reviews: 34,
    prevPrice: 140,
    newPrice: 50,
    company: "Vans",
    color: "white",
    category: "Dress Shirts",
    colors: ["White", "Black", "Brown"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Classic loafer design with modern comfort.",
    material: "Leather",
    weight: "400g",
    dimensions: "28 x 18 x 7 cm"
  },
  {
    id: 8,
    img: dress_8,
    title: "Nike Zoom Freak",
    reviews: 92,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "green",
    category: "Dress Shirts",
    colors: ["Green", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    rating: 5,
    description: "Responsive basketball shoes with Zoom Air cushioning.",
    material: "Mesh",
    weight: "420g",
    dimensions: "29 x 19 x 9 cm"
  },
  {
    id: 9,
    img: dress_9,
    title: "Nike Men's Sneaker",
    reviews: 56,
    prevPrice: 140,
    newPrice: 200,
    company: "Adidas",
    color: "blue",
    category: "Polo Shirts",
    colors: ["Blue", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "Versatile sneakers for sports and casual wear.",
    material: "Synthetic",
    weight: "410g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 10,
    img: dress_10,
    title: "PUMA BLACK-OCE",
    reviews: 78,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "green",
    category: "Polo Shirts",
    colors: ["Green", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "Stylish sneakers with cushioned soles.",
    material: "Leather",
    weight: "390g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 11,
    img: dress_11,
    title: "Pacer Future Sneaker",
    reviews: 45,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "red",
    category: "T-Shirts",
    colors: ["Red", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Futuristic design with comfortable fit.",
    material: "Mesh",
    weight: "370g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 12,
    img: dress_12,
    title: "Unisex-Adult Super",
    reviews: 67,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "black",
    category: "T-Shirts",
    colors: ["Black", "White", "Gray"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "Unisex sneakers for everyday wear.",
    material: "Synthetic",
    weight: "380g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 13,
    img: dress_13,
    title: "Roma Basic Sneaker",
    reviews: 34,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "white",
    category: "Flannel Shirts",
    colors: ["White", "Black", "Blue"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Basic sneakers with minimalist design.",
    material: "Leather",
    weight: "400g",
    dimensions: "28 x 18 x 8 cm"
  },
  {
    id: 14,
    img: dress_14,
    title: "Pacer Future Doubleknit",
    reviews: 56,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "black",
    category: "Flannel Shirts",
    colors: ["Black", "Gray", "Red"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "Breathable doubleknit upper for comfort.",
    material: "Knit",
    weight: "360g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 15,
    img: dress_15,
    title: "Fusion Evo Golf Shoe",
    reviews: 23,
    prevPrice: 140,
    newPrice: 100,
    company: "Puma",
    color: "green",
    category: "Flannel Shirts",
    colors: ["Green", "White", "Black"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Specialized golf shoes with excellent grip.",
    material: "Leather",
    weight: "420g",
    dimensions: "29 x 19 x 9 cm"
  },
  {
    id: 16,
    img: dress_16,
    title: "Rainbow Chex Skate",
    reviews: 89,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "red",
    category: "Flannel Shirts",
    colors: ["Red", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 5,
    description: "Classic skate shoes with colorful design.",
    material: "Canvas",
    weight: "350g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 17,
    img: dress_1,
    title: "Low-Top Trainers",
    reviews: 45,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "white",
    category: "Henley Shirts",
    colors: ["White", "Black", "Blue"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Simple low-top trainers for casual outfits.",
    material: "Canvas",
    weight: "340g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 18,
    img: dress_2,
    title: "Vans Unisex Low-Top",
    reviews: 67,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "blue",
    category: "Henley Shirts",
    colors: ["Blue", "Black", "White"],
    sizes: ["S", "M", "L"],
    rating: 4,
    description: "Unisex low-top shoes with durable construction.",
    material: "Canvas",
    weight: "350g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 19,
    img: dress_3,
    title: "Classic Bandana Sneakers",
    reviews: 34,
    prevPrice: 140,
    newPrice: 50,
    company: "Nike",
    color: "black",
    category: "Henley Shirts",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L"],
    rating: 3,
    description: "Sneakers with classic bandana print design.",
    material: "Canvas",
    weight: "360g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 20,
    img: dress_4,
    title: "Chunky High Heel",
    reviews: 56,
    prevPrice: 140,
    newPrice: 50,
    company: "Vans",
    color: "black",
    category: "Henley Shirts",
    colors: ["Black", "White", "Brown"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Fashionable chunky heel shoes for women.",
    material: "Synthetic",
    weight: "450g",
    dimensions: "28 x 18 x 12 cm"
  },
  {
    id: 21,
    img: dress_5,
    title: "Slip On Stiletto High Heel",
    reviews: 23,
    prevPrice: 140,
    newPrice: 100,
    company: "Puma",
    color: "black",
    category: "Dress Shirts",
    colors: ["Black", "Red", "Nude"],
    sizes: ["S", "M"],
    rating: 3,
    description: "Elegant stiletto heels for formal occasions.",
    material: "Patent Leather",
    weight: "380g",
    dimensions: "27 x 17 x 11 cm"
  },
  {
    id: 22,
    img: dress_6,
    title: "DREAM PAIRS Court Shoes",
    reviews: 45,
    prevPrice: 140,
    newPrice: 150,
    company: "Nike",
    color: "red",
    category: "Dress Shirts",
    colors: ["Red", "Black", "White"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Classic court shoes with comfortable fit.",
    material: "Leather",
    weight: "350g",
    dimensions: "27 x 17 x 7 cm"
  },
  {
    id: 23,
    img: dress_7,
    title: "Low Mid Block Heels",
    reviews: 34,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "black",
    category: "Dress Shirts",
    colors: ["Black", "Brown", "Nude"],
    sizes: ["S", "M"],
    rating: 3,
    description: "Comfortable block heels for all-day wear.",
    material: "Suede",
    weight: "400g",
    dimensions: "27 x 17 x 8 cm"
  },
  {
    id: 24,
    img: dress_8,
    title: "Chunky High Heel",
    reviews: 56,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Dress Shirts",
    colors: ["Black", "White", "Silver"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Trendy chunky heels with platform sole.",
    material: "Synthetic",
    weight: "420g",
    dimensions: "28 x 18 x 10 cm"
  },
  {
    id: 25,
    img: dress_9,
    title: "Amore Fashion Stilettos",
    reviews: 23,
    prevPrice: 140,
    newPrice: 150,
    company: "Adidas",
    color: "white",
    category: "Polo Shirts",
    colors: ["White", "Black", "Gold"],
    sizes: ["S", "M"],
    rating: 3,
    description: "Elegant stilettos for special occasions.",
    material: "Patent Leather",
    weight: "350g",
    dimensions: "27 x 17 x 12 cm"
  },
  {
    id: 26,
    img: dress_10,
    title: "Bridal Sandals Glitter",
    reviews: 45,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Polo Shirts",
    colors: ["Black", "Silver", "Gold"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Sparkling bridal sandals for weddings.",
    material: "Satin",
    weight: "300g",
    dimensions: "26 x 16 x 6 cm"
  },
  {
    id: 27,
    img: dress_11,
    title: "Wedding Prom Bridal",
    reviews: 34,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "T-Shirts",
    colors: ["Black", "White", "Ivory"],
    sizes: ["S", "M"],
    rating: 3,
    description: "Elegant bridal shoes for formal events.",
    material: "Satin",
    weight: "320g",
    dimensions: "26 x 16 x 7 cm"
  },
  {
    id: 28,
    img: dress_12,
    title: "Wedding Prom Bridal",
    reviews: 56,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "T-Shirts",
    colors: ["Black", "Silver", "Gold"],
    sizes: ["S", "M"],
    rating: 4,
    description: "Classic bridal pumps with comfortable heel.",
    material: "Patent Leather",
    weight: "340g",
    dimensions: "26 x 16 x 8 cm"
  }
];

export default data;