import dress_1 from '../assets/dress_images/dress_1.jpeg';
import dress_2 from '../assets/dress_images/dress_2.jpeg';
import dress_3 from '../assets/dress_images/dress_3.jpeg';
import dress_4 from '../assets/dress_images/dress_4.jpeg';
import dress_5 from '../assets/dress_images/dress_5.jpeg';
import dress_6 from '../assets/dress_images/dress_6.jpeg';
import dress_7 from '../assets/dress_images/dress_7.jpeg';
import dress_8 from '../assets/dress_images/dress_8.jpeg';
import dress_9 from '../assets/dress_images/dress_9.jpeg';
import dress_10 from '../assets/dress_images/dress_10.jpg';
import dress_11 from '../assets/dress_images/dress_11.jpeg';
import dress_12 from '../assets/dress_images/dress_12.jpeg';
import dress_13 from '../assets/dress_images/dress_13.jpeg';
import dress_14 from '../assets/dress_images/dress_14.jpeg';
import dress_15 from '../assets/dress_images/dress_15.jpeg';
import dress_16 from '../assets/dress_images/dress_16.jpeg';


const data = [
  {
    id:1,
    img: dress_1,
    title: "Nike Air Monarch IV",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "Off-White",
    category: "Henley Shirts ",
  },
  {
    id:2,
    img: dress_2,
    title: "Nike Air Vapormax Plus",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "red",
    category: "Henley Shirts ",
  },
  {
    id:3,
    img: dress_3,
    title: "Nike Waffle One Sneaker",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "green",
    category: "Henley Shirts ",
  },
  {
    id:4,
    img: dress_4,
    title: "Nike Running Shoe",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Adidas",
    color: "black",
    category: "Henley Shirts ",
  },
  {
    id:5,
    img: dress_5,
    title: "Flat Slip On Pumps",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Vans",
    color: "green",
    category: "Dress Shirts",
  },
  {
    id:6,
    img: dress_6,
    title: "Knit Ballet Flat",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Dress Shirts",
  },
  {
    id:7,
    img: dress_7,
    title: "Loafer Flats",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Vans",
    color: "white",
    category: "Dress Shirts",
  },
  {
    id:8,
    img: dress_8,
    title: "Nike Zoom Freak",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "green",
    category: "Dress Shirts",
  },
  {
    id:9,
    img: dress_9,
    title: "Nike Men's Sneaker",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Adidas",
    color: "blue",
    category: "Polo Shirts",
  },
  {
    id:10,
    img: dress_10,
    title: "PUMA BLACK-OCE",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "green",
    category: "Polo Shirts",
  },
  {
    id:11,
    img: dress_11,
    title: "Pacer Future Sneaker",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "red",
    category: "T-Shirts",
  },
  {
    id:12,
    img: dress_12,
    title: "Unisex-Adult Super",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "black",
    category: "T-Shirts",
  },
  {
    id:13,
    img: dress_13,
    title: "Roma Basic Sneaker",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "white",
    category: "Flannel Shirts",
  },
  {
    id:14,
    img: dress_14,
    title: "Pacer Future Doubleknit",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Puma",
    color: "black",
    category: "Flannel Shirts",
  },
  {
    id:15,
    img: dress_15,
    title: "Fusion Evo Golf Shoe",
    reviews: 123,
    prevPrice: 140,
    newPrice: 100,
    company: "Puma",
    color: "green",
    category: "Flannel Shirts",
  },
  {
    id:16,
    img: dress_16,
    title: "Rainbow Chex Skate",
    reviews: 123,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "red",
    category: "Flannel Shirts",
  },
  {
    id:17,
    img: dress_1,
    title: "Low-Top Trainers",
    reviews: 123,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "white",
    category: "Henley Shirts",
  },
  {
    id:18,
    img: dress_2,
    title: "Vans Unisex Low-Top",
    reviews: 123,
    prevPrice: 140,
    newPrice: 100,
    company: "Vans",
    color: "blue",
    category: "Henley Shirts",
  },
  {
    id:19,
    img: dress_3,
    title: "Classic Bandana Sneakers",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Nike",
    color: "black",
    category: "Henley Shirts",
  },
  {
    id:20,
    img: dress_4,
    title: "Chunky High Heel",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Vans",
    color: "black",
    category: "Henley Shirts",
  },
  {
    id:21,
    img: dress_5,
    title: "Slip On Stiletto High Heel",
    reviews: 123,
    prevPrice: 140,
    newPrice: 100,
    company: "puma",
    color: "black",
    category: "Dress Shirts",
  },
  {
    id:22,
    img: dress_6,
    title: "DREAM PAIRS Court Shoes",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Nike",
    color: "red",
    category: "Dress Shirts",
  },
  {
    id:23,
    img: dress_7,
    title: "Low Mid Block Heels",
    reviews: 123,
    prevPrice: 140,
    newPrice: 200,
    company: "Nike",
    color: "black",
    category: "Dress Shirts",
  },
  {
    id:24,
    img: dress_8,
    title: "Chunky High Heel",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Dress Shirts",
  },
  {
    id:25,
    img: dress_9,
    title: "Amore Fashion Stilettos",
    reviews: 123,
    prevPrice: 140,
    newPrice: 150,
    company: "Adidas",
    color: "white",
    category: "Polo Shirts",
  },
  {
    id:26,
    img: dress_10,
    title: "Bridal Sandals Glitter",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "Polo Shirts",
  },
  {
    id:27,
    img: dress_11,
    title: "Wedding Prom Bridal",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "T-Shirts",
  },
  {
    id:28,
    img: dress_12,
    title: "Wedding Prom Bridal",
    reviews: 123,
    prevPrice: 140,
    newPrice: 50,
    company: "Adidas",
    color: "black",
    category: "T-Shirts",
  },
];

export default data;
